# permissions for end users to view proxableservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxableservice-viewer-role
rules:
- apiGroups:
  - binding.operators.coreos.com
  resources:
  - proxableservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - binding.operators.coreos.com
  resources:
  - proxableservices/status
  verbs:
  - get
