# permissions for end users to edit proxableservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxableservice-editor-role
rules:
- apiGroups:
  - binding.operators.coreos.com
  resources:
  - proxableservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - binding.operators.coreos.com
  resources:
  - proxableservices/status
  verbs:
  - get
