# permissions for end users to edit serviceresourcemaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceresourcemap-editor-role
rules:
- apiGroups:
  - binding.operators.coreos.com
  resources:
  - serviceresourcemaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - binding.operators.coreos.com
  resources:
  - serviceresourcemaps/status
  verbs:
  - get
