# permissions for end users to view serviceresourcemaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceresourcemap-viewer-role
rules:
- apiGroups:
  - binding.operators.coreos.com
  resources:
  - serviceresourcemaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - binding.operators.coreos.com
  resources:
  - serviceresourcemaps/status
  verbs:
  - get
