# permissions for end users to view serviceproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceproxy-viewer-role
rules:
- apiGroups:
  - binding.operators.coreos.com
  resources:
  - serviceproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - binding.operators.coreos.com
  resources:
  - serviceproxies/status
  verbs:
  - get
