apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: srm-rds-psql-sample
  namespace: srm-rds-sample
spec:
  allocatedStorage: 20
  dbInstanceClass: db.t3.micro
  dbInstanceIdentifier: rds-psql-sample
  engine: postgres
  engineVersion: "14"
  masterUsername: "postgres"
  masterUserPassword:
    namespace: srm-rds-sample
    name: srm-rds-psql-sample-password
    key: password
