apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: sbo-srm
  labels:
    servicebinding.io/controller: "true"
rules:
- apiGroups:
  - "binding.operators.coreos.com"
  resources:
  - "serviceproxies"
  verbs:
  - get
  - list
  - watch

