apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-service-binding-operator
  namespace: openshift-operators
spec:
  channel: stable
  name: rh-service-binding-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: sbo-srm
  labels:
    servicebinding.io/controller: "true"
rules:
- apiGroups:
  - "binding.operators.coreos.com"
  resources:
  - "serviceproxies"
  verbs:
  - get
  - list
  - watch

