apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-service-binding-operator
  namespace: openshift-operators
spec:
  channel: stable
  name: rh-service-binding-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
