apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceResourceMap
metadata:
  name: serviceresourcemap-sample
  namespace: srm-sample
spec:
  service_kind_reference:
    api_group: "apps/v1"
    kind: "deployments"
  service_map:
    type: "postgresql"
    host: "path={.metadata.name}.{.metadata.namespace}"
    port: "path={.spec.template.spec.containers[0].ports[0].containerPort}"
    service.binding: "path={.spec.template.spec.volumes[0].secret.secretName},objectType=Secret"

